name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7, 3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-build
          ruby-build ${{ matrix.ruby }} /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64
          touch /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64.complete
        env:
          PATH: /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64/bin:$PATH

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test
